xapiservice:
  image: slidewiki/xapiservice:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=xapiservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=xapiservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - URL_PLATFORM=https://platform.experimental.slidewiki.org
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_PDF=https://pdfservice.experimental.slidewiki.org
    - SERVICE_URL_XAPI=https://xapiservice.experimental.slidewiki.org
    - SERVICE_URL_NOTIFICATION=https://notificationservice.experimental.slidewiki.org
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - JWT_SERIAL=69aac7f95a9152cd4ae7667c80557c284e413d748cca4c5715b3f02020a5ae1b
