xapiservice:
  image: slidewiki/xapiservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=xapiservice.experimental.slidewiki.org
    - LETSENCRYPT_HOST=xapiservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
